# frozen_string_literal: true

source 'https://rubygems.org'

gem 'falcon', '~> 0.47'
gem 'restate-sdk'
gem 'sorbet-runtime'

group :development do
  gem 'rubocop', require: false
  gem 'sorbet', require: false
  gem 'tapioca', require: false
end
